version: '3'

services:
    redis:
        image: 'redis:5.0.5'
        container_name: 'redis'
        ports:
            - '6379:6379'
        # networks:
        #   - "app-network"

    postgres:
        image: 'postgres:16.2'
        container_name: 'postgres'
        restart: always
        ports:
            - '5432:5432'
        environment:
            # dummy setup
            POSTGRES_USER: 'zkarim'
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DB: 'fundraiser'
