# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# Testing a basic CI
name: Master Pull Requests CI

on:
    # push:
    # branches: [ "master" ]
    pull_request:
        branches: ['master']

jobs:
    default:
        name: All-in-one
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis:5.0.5
                options: --entrypoint redis-server
                ports:
                    - 6379:6379

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build --if-present
            - name: Code Formatting
              run: npm run format:verify
            - name: Tests
              run: npm test
